const KEY='arjuna-productivity-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[{id:1,title:'Review portfolio README improvements',when:'Today',priority:true,done:false},{id:2,title:'Solve one DSA problem',when:'Today',priority:false,done:false},{id:3,title:'Write the next Arjuna learning module',when:'This week',priority:false,done:false}],notes:[],meetings:[],sessions:0};
let taskFilter='all',timerSeconds=1500,timerRunning=false,timerInterval=null;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function formatDate(value){if(!value)return '';const d=new Date(value);return d.toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function render(){const open=state.tasks.filter(t=>!t.done);$('taskNavCount').textContent=open.length;$('completedStat').textContent=state.tasks.filter(t=>t.done).length;$('priorityStat').textContent=state.tasks.filter(t=>t.priority&&!t.done).length;$('sessionsStat').textContent=state.sessions;
 const rows=state.tasks.filter(t=>!t.done).slice(0,4).map(taskRow).join('');$('overviewTasks').innerHTML=rows||'<p class="empty-state">Nothing urgent. Add a task for your next meaningful step.</p>';$('fullTaskList').innerHTML=state.tasks.filter(t=>taskFilter==='all'||(taskFilter==='open'&&!t.done)||(taskFilter==='done'&&t.done)||(taskFilter==='priority'&&t.priority&&!t.done)).map(taskRow).join('')||'<p class="empty-state">No tasks in this view.</p>';
 $('savedNotes').innerHTML=state.notes.length?state.notes.slice().reverse().map(n=>`<article class="note-card"><h4>${escapeHtml(n.title||'Untitled note')}</h4><p>${escapeHtml(n.body).replace(/\n/g,'<br>')}</p><small>${escapeHtml(n.date)}</small></article>`).join(''):'<div class="note-card"><h4>Your saved notes will appear here.</h4><p>Capture an idea on the left and save it locally.</p></div>';
 $('meetingList').innerHTML=state.meetings.length?state.meetings.slice().sort((a,b)=>new Date(a.time)-new Date(b.time)).map(m=>`<div class="meeting-row"><strong>${escapeHtml(m.title)}</strong><small>${formatDate(m.time)}</small><small class="meeting-outcome">${escapeHtml(m.outcome||'Outcome not set yet')}</small></div>`).join(''):'<p class="empty-state">No meetings planned yet.</p>';save()}
function taskRow(t){return `<div class="task-row" data-id="${t.id}"><button class="task-check ${t.done?'done':''}" aria-label="Mark task ${t.done?'open':'complete'}">${t.done?'✓':''}</button><div class="task-info"><strong class="${t.done?'strike':''}">${escapeHtml(t.title)}</strong><small>${escapeHtml(t.when)}</small></div>${t.priority&&!t.done?'<span class="priority-pill">Priority</span>':''}</div>`}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')};function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true')}
function showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${view}View`).classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:'Good afternoon, Dhananjay.',tasks:'Your work queue.',notes:'Your thought space.',planner:'Your week, with intention.'};$('pageTitle').textContent=titles[view]||titles.overview;window.scrollTo({top:0,behavior:'smooth'});if(window.innerWidth<651)$('sidebar').classList.remove('open')}
function updateTimer(){const min=String(Math.floor(timerSeconds/60)).padStart(2,'0'),sec=String(timerSeconds%60).padStart(2,'0');$('timerDisplay').textContent=`${min}:${sec}`;$('timerProgress').style.width=`${Math.max(0,(1500-timerSeconds)/1500*100)}%`;$('timerToggle').textContent=timerRunning?'Pause':'Start';$('timerLabel').textContent=timerRunning?'Deep work in progress':'Ready when you are'}
function toggleTimer(){timerRunning=!timerRunning;if(timerRunning){timerInterval=setInterval(()=>{if(timerSeconds>0){timerSeconds--;updateTimer()}else{clearInterval(timerInterval);timerRunning=false;state.sessions++;save();render();toast('Focus session complete. Take a breath.')}},1000)}else clearInterval(timerInterval);updateTimer()}
async function askArjuna(message){const lower=message.toLowerCase();let fallback='Start by naming the outcome. Then choose the smallest action that proves you are moving toward it.';if(lower.includes('meeting'))fallback='Meeting brief: define the decision, list the two facts that matter, and end with one owner plus a next date.';if(lower.includes('task')||lower.includes('plan'))fallback='Your next 20 minutes: choose one priority task, silence distractions, and finish a visible first version before optimizing it.';try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,context:{tasks:state.tasks,meetings:state.meetings}})});if(response.ok){const data=await response.json();if(data.reply)return data.reply}}catch(e){}return fallback}
function addChat(text,who){const box=$('chatMessages');const el=document.createElement('div');el.className=`chat-bubble ${who}`;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){showView(nav.dataset.view);return}const close=e.target.closest('[data-close]');if(close)closeModal(close.dataset.close);const row=e.target.closest('.task-row');if(row&&e.target.closest('.task-check')){const t=state.tasks.find(x=>x.id==row.dataset.id);if(t){t.done=!t.done;save();render();toast(t.done?'Task completed':'Task reopened')}}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{taskFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));
$('newTaskButton').onclick=()=>{openModal('taskModal');$('taskTitleInput').focus()};$('quickAddTask').onclick=()=>{openModal('taskModal');$('taskTitleInput').focus()};$('taskForm').onsubmit=e=>{e.preventDefault();state.tasks.push({id:Date.now(),title:$('taskTitleInput').value.trim(),when:$('taskWhen').value,priority:$('taskPriority').checked,done:false});e.target.reset();closeModal('taskModal');render();toast('Task added to your day')};
$('newMeetingButton').onclick=()=>openModal('meetingModal');$('meetingForm').onsubmit=e=>{e.preventDefault();state.meetings.push({id:Date.now(),title:$('meetingTitleInput').value.trim(),time:$('meetingTimeInput').value,outcome:$('meetingOutcomeInput').value.trim()});e.target.reset();closeModal('meetingModal');render();toast('Meeting added')};
$('saveNoteButton').onclick=()=>{const title=$('noteTitle').value.trim(),body=$('noteBody').value.trim();if(!body){toast('Write something before saving');return}state.notes.push({id:Date.now(),title,body,date:new Date().toLocaleString()});$('noteTitle').value='';$('noteBody').value='';$('noteStatus').textContent='Saved just now';render();toast('Note saved locally')};
$('timerToggle').onclick=toggleTimer;$('timerReset').onclick=()=>{clearInterval(timerInterval);timerRunning=false;timerSeconds=1500;updateTimer()};$('startFocusFromHero').onclick=()=>{showView('overview');if(!timerRunning)toggleTimer()};
$('openAssistant').onclick=()=>$('assistantDrawer').classList.add('open');$('closeAssistant').onclick=()=>$('assistantDrawer').classList.remove('open');$('insightAsk').onclick=()=>$('assistantDrawer').classList.add('open');$('prepAsk').onclick=()=>{showView('planner');$('assistantDrawer').classList.add('open');$('chatInput').value='Prepare me for my next meeting'};
$('chatForm').onsubmit=async e=>{e.preventDefault();const input=$('chatInput'),message=input.value.trim();if(!message)return;input.value='';addChat(message,'user');const loading='Thinking...';addChat(loading,'assistant');const last=$('chatMessages').lastElementChild;last.textContent=await askArjuna(message)};
$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('openSettings').onclick=()=>toast('Preferences will be added in the next iteration');$('commandButton').onclick=()=>toast('Tip: use the sidebar to jump between workspace views');
render();updateTimer();